# App
app:
  name: GoethApi
  version: 0.1

env: staging

debug: true

# Database settings
database:
  connection: postgres
  host: localhost
  dbname: database_name
  user: database_login
  password: database_password

# Blockchain settings
blockchain:
  rawurl: url_or_raw_to_blockchain_node
  keystorepath: path_to_blockchain_keystore

# Blockchain account
account:
  address: your_public_address
  keystore: your_path_to_account_file
  json: 'your_json_file_data'
  passphrase: your_account_passphrase
