# App
app:
  name: GoethApi

env: staging

debug: true

# Blockchain settings
blockchain:
  rawurl: url_or_raw_to_blockchain_node
  keystorepath: path_to_blockchain_keystore

# Blockchain account
account:
  key: 'your_json_file_data'
  passphrase: your_account_passphrase
